import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";
// src/app/api/auth/signup/route.ts
import { z } from "zod";
import { sendWelcomeEmail } from "@/lib/email";
import { prisma } from "@/lib/prisma";
import { authRateLimiter, logSecurityEvent } from "@/lib/security";

const signupSchema = z.object({
  name: z.string().min(1, "Name is required").max(100, "Name too long"),
  email: z.string().email("Invalid email format").max(255, "Email too long"),
  // REMOVED: Password is now set during registration completion after approval
  phone: z.string().optional(),
  level: z.enum([
    "PRE_PRELIMINARY",
    "PRELIMINARY",
    "PRE_JUVENILE",
    "JUVENILE",
    "INTERMEDIATE",
    "NOVICE",
    "JUNIOR",
    "SENIOR",
  ]),
  maxLessonsPerWeek: z.number().int().positive().optional().default(3),
  emergencyContact: z
    .object({
      name: z.string(),
      phone: z.string(),
      relationship: z.string(),
    })
    .optional(),
  parentConsent: z.boolean().default(false),
});

export async function POST(req: NextRequest) {
  try {
    // Rate limiting
    const clientIP =
      req.headers.get("x-forwarded-for") || req.headers.get("x-real-ip") || "unknown";
    if (!authRateLimiter.isAllowed(clientIP)) {
      logSecurityEvent("RATE_LIMIT_EXCEEDED", {
        endpoint: "/api/auth/signup",
        ip: clientIP,
      });
      return NextResponse.json(
        { message: "Too many signup attempts. Please try again later." },
        { status: 429 },
      );
    }

    // Parse request body with size limit
    const body = await req.json();
    console.log("Signup request received:", { ...body, password: "[REDACTED]" });
    const result = signupSchema.safeParse(body);

    if (!result.success) {
      console.error("Signup validation failed:", {
        body,
        errors: result.error.format(),
        issues: result.error.issues,
      });
      logSecurityEvent("INVALID_SIGNUP_DATA", {
        ip: clientIP,
        errors: result.error.format(),
      });
      return NextResponse.json(
        { message: "Invalid data", errors: result.error.format() },
        { status: 400 },
      );
    }

    const {
      name,
      email,
      phone,
      level,
      maxLessonsPerWeek,
      emergencyContact,
      parentConsent,
    } = result.data;

    // REMOVED: Password validation - password will be set during registration completion

    // Check if email already exists
    const existingUser = await prisma.user.findUnique({
      where: { email: email.toLowerCase() },
    });

    if (existingUser) {
      console.log("Signup failed: Email already in use:", email.toLowerCase());
      logSecurityEvent("DUPLICATE_EMAIL_SIGNUP", {
        ip: clientIP,
        email: email.toLowerCase(),
      });
      return NextResponse.json({ message: "Email already in use" }, { status: 400 });
    }

    // REMOVED: Password hashing - password will be set during registration completion

    // Test database connection
    console.log("Testing database connection...");
    try {
      await prisma.$queryRaw`SELECT 1`;
      console.log("Database connection successful");
    } catch (dbError) {
      console.error("Database connection failed:", dbError);
      throw new Error("Database connection failed");
    }

    // Create user and student profile in a transaction
    console.log("Starting database transaction...");
    console.log("Data to create:", {
      name,
      email: email.toLowerCase(),
      phone: phone || null,
      level,
      maxLessonsPerWeek,
      emergencyContact: emergencyContact || null,
      parentConsent,
    });

    const user = await prisma.$transaction(async (tx) => {
      console.log("Creating user...");
      // Create user first (ID auto-generated by Prisma) - NO PASSWORD YET
      const newUser = await tx.user.create({
        data: {
          name,
          email: email.toLowerCase(),
          password: null, // Password will be set during registration completion
          role: "STUDENT",
        },
      });
      console.log("User created successfully:", newUser.id);

      console.log("Creating student profile...");
      // Create student profile linked to user (ID auto-generated by Prisma)
      const student = await tx.student.create({
        data: {
          userId: newUser.id,
          phone: phone || null,
          level,
          maxLessonsPerWeek,
          emergencyContact: emergencyContact || undefined,
          parentConsent,
        },
      });
      console.log("Student profile created successfully:", student.id);

      return {
        ...newUser,
        Student: student,
      };
    });
    console.log("Transaction completed successfully");

    // Send welcome email after successful user creation (don't fail if email fails)
    console.log("=== EMAIL SENDING ATTEMPT ===");
    console.log("RESEND_API_KEY exists:", !!process.env.RESEND_API_KEY);
    console.log("RESEND_API_KEY length:", process.env.RESEND_API_KEY?.length || 0);
    console.log("Sending welcome email to:", user.email);
    
    try {
      const emailResult = await sendWelcomeEmail(user.email, user.name || "");
      console.log("✅ Welcome email sent successfully:", emailResult);
    } catch (emailError) {
      console.error("❌ Failed to send welcome email:", emailError);
      // Don't fail the whole signup if email fails
    }
    
    console.log("=== EMAIL SENDING COMPLETE ===");

    // Return success with user data (excluding password)
    const { password: _, ...userData } = user;
    return NextResponse.json(
      {
        message: "Account created successfully",
        user: userData,
      },
      { status: 201 },
    );
  } catch (error) {
    console.error("Error creating user:", error);
    console.error("Error stack:", error instanceof Error ? error.stack : "No stack trace");
    console.error("Error details:", {
      name: error instanceof Error ? error.name : "Unknown",
      message: error instanceof Error ? error.message : String(error),
    });
    return NextResponse.json({ 
      message: "Failed to create account",
      error: error instanceof Error ? error.message : String(error)
    }, { status: 500 });
  }
}
